### ISSUE TITLE
app show blank page after change theme from light to dark

### ISSUE THREAD

**Issue by muhammadarif1** [hakkikaancaliskan/GuvenliNot#18]
**Describe the bug**
the app displays a dark page after changing the theme from light to dark at the password change section
**To Reproduce**
1.  open the app and login
2. Click on change password
3.change pasword and save 
4. click on dot 3 option
5. chose change theme then change the theme to dark 
6. go back and see error

**Expected behavior**
this application will still work perfectly after the theme is changed

*BUG RECORDING**
https://youtu.be/voVE6Y8xNcA
**Smartphone (please complete the following information):**
 - Device: [e.g. oppo neo 7]
 - OS: [e.g. Android 6.0]

**Comment by hakkikaancaliskan** [comment]
Problem is about to android is starting apps as android's default theme. If its white, predicts Guvenli Not as white themed app. If black, predicts Guvenli Not as black themed app. In Guvenli Not we apply theme in Login Activity but I can't control before the startup of Login Activity
I'll take a look about it
