### ISSUE TITLE
New Logo Design

### ISSUE THREAD

**Issue by zularizal** [hakkikaancaliskan/GuvenliNot#2]
Hi @hakkikaancaliskan  , I'm a graphic designer after I review your project, The current logo looks simple and generic. I want to make an elegant and modern logo. And this is free for your project. What do you think?

**Comment by hakkikaancaliskan** [comment]
Hello my old friend :)
I'll be very happy with your support. I think you get the idea of app. Thanks for your support.

**Comment by zularizal** [comment]
Hi @hakkikaancaliskan , this is my logo design for your project. This logo is inspired by the letter 'G' from initial 'Givendi', a note and a padlock. Then I combine them. What do you think? And what about the icon?

If something wants to be changed, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/45592953-105be380-b9a5-11e8-96a5-a1298329734b.png)

**Comment by hakkikaancaliskan** [comment]
They are really great. I loved them. For icon I think A is better. I selected A. Thanks.

**Comment by hakkikaancaliskan** [comment]
Merged pull request. Thank you so much.
