### ISSUE TITLE
Using Database instead of SharedPreferences

### ISSUE THREAD

**Issue by hakkikaancaliskan** [hakkikaancaliskan/GuvenliNot#4]
I want to implement database for more security but I couldn't. Any help will be really appreciated.

**Comment by deepakkumarece14** [comment]
Isn't is useless to implement the database just for the one entry and since you have already Hashed the password it's already secured.

**Comment by hakkikaancaliskan** [comment]
@deepakkumarece14 I'm planning to implement ability to add note more than 1.

**Comment by deepakkumardk** [comment]
okay, I got it, I have run your application through android studio. So, now you want to implement the database feature in it to save the multiple notes. Do you want to use the [Architecture Components](https://developer.android.com/topic/libraries/architecture/) like Room, ViewModel, LiveData.

**Comment by hakkikaancaliskan** [comment]
I've no such thing about room, livedata etc. If you want to implement them, I will be grateful.

**Comment by hakkikaancaliskan** [comment]
Solved. Thanks to @deepakkumardk

**Comment by hakkikaancaliskan** [comment]
@deepakkumardk
Hi old friend :))
As you can notice I go further app. Now I'm planning to add search function. Looks like I need LiveData and real changes on adapter and you know I'm so bad on database :(
Could you help me?
If you say yes, I can explain how search function will work.

**Comment by deepakkumardk** [comment]
Hello Hakki Kaan Caliskan

It's nice to hear that you are adding new features to the app and I would
love to work with you. Give me the details and I will work on it in my free
time.

Thanks & Regards
Deepak Kumar

**Comment by hakkikaancaliskan** [comment]
Thank you so much :)
First of all ui is ready. I'm planning to search with current recyclerview. There will be a LiveData<MutableList<Note>> and will refresh recyclerview with it. Also 1 adapter is enough because I'm planning to change noteList to LiveData.
You should make changes on adapter and refresh current recyclerview with that LiveData list. Because of List to LiveData List changes, there will so much thing to change :(
Thanks for your all effort :))

**Comment by hakkikaancaliskan** [comment]
I've make changes for you in code and prepared for apk to see latest ui.
[app-alpha.zip](https://github.com/hakkikaancaliskan/GuvenliNot/files/3133937/app-alpha.zip)

**Comment by deepakkumardk** [comment]
Hello @hakkikaancaliskan 
I am getting this error after cloning it and building it in Android Studio:

> ERROR: Illegal character in opaque part at index 2: D:\key.jks


Please update your file as in this open source project: [https://github.com/SimpleMobileTools/Simple-Notes/blob/master/keystore.properties_sample](https://github.com/SimpleMobileTools/Simple-Notes/blob/master/keystore.properties_sample)

**Comment by hakkikaancaliskan** [comment]
@deepakkumardk
Just delete this :)) 
https://github.com/hakkikaancaliskan/GuvenliNot/blob/master/app/build.gradle#L7

**Comment by deepakkumardk** [comment]
Hi @hakkikaancaliskan 
Sorry for the delay, I was out of station. I have made a PR, check this out.

**Comment by hakkikaancaliskan** [comment]
Hi @deepakkumardk 
Thank you so much. Working on your pr.

**Comment by hakkikaancaliskan** [comment]
Hi @deepakkumardk 
Thanks for everything. Working perfectly.
If you wanna work on other things [https://github.com/hakkikaancaliskan/GuvenliNot/issues](Issues).
